name: Client CI

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/client/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/client/**'
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Installing dependencies
        run: yarn
      -
        name: Building
        working-directory: ./packages/client
        run: yarn build
      -
        name: Testing
        working-directory: ./packages/client
        run: yarn test