name: API-JS CI

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/api-js/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/api-js/**'
  workflow_dispatch:

jobs:
  ci:
    name: API-JS CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Installing dependencies
        run: yarn install
      -
        name: Building
        working-directory: ./packages/api-js
        run: yarn build
      -
        name: Testing
        working-directory: ./packages/api-js
        run: yarn test